// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/3/19 17:37:01
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/tanshow/Developer/trade-arena/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tanshow/Developer/trade-arena/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tanshow/Developer/trade-arena/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tanshow/Developer/trade-arena/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tanshow/Developer/trade-arena/frontend/plugins/**/*.{js,ts,mjs}","/Users/tanshow/Developer/trade-arena/frontend/composables/**/*.{js,ts,mjs}","/Users/tanshow/Developer/trade-arena/frontend/utils/**/*.{js,ts,mjs}","/Users/tanshow/Developer/trade-arena/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tanshow/Developer/trade-arena/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tanshow/Developer/trade-arena/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tanshow/Developer/trade-arena/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;